### ISSUE TITLE
quick start error

### ISSUE THREAD

**Issue by joshuia** [DeepGraphLearning/graphvite#11]
when I use "graphvite baseline quick start", it shows:

Check failed: error == cudaSuccess CUDA error CUDA driver version is insufficient for CUDA runtime version at /lustre04/scratch/zhuzhaoc/conda/conda-bld/graphvite_1565206157156/work/include/core/solver.h:182

but "nvcc -V" shows:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88

is cuda 9.2 error ?

**Comment by joshuia** [comment]
all error message:

Check failed: error == cudaSuccess CUDA error CUDA driver version is insufficient for CUDA runtime version at /lustre04/scratch/zhuzhaoc/conda/conda-bld/graphvite_1565206157156/work/include/core/solver.h:182
*** Check failure stack trace: ***
    @     0x7f92dc7294dd  google::LogMessage::Fail()
    @     0x7f92dc731071  google::LogMessage::SendToLog()
    @     0x7f92dc728ecd  google::LogMessage::Flush()
    @     0x7f92dc72a76a  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f92db37e0b9  graphvite::CudaCheck()
    @     0x7f92db496105  graphvite::SolverMixin<>::SolverMixin()
    @     0x7f92db4d46b5  _ZZN8pybind1112cpp_function10initializeIZNS_6detail8initimpl11constructorIJSt6vectorIiSaIiEEimEE7executeINS_6class_IN9graphvite11GraphSolverILm128EfjEEJEEEJNS_10call_guardIJNS_18gil_scoped_releaseEEEENS_5arg_vESI_SI_ELi0EEEvRT_DpRKT0_EUlRNS2_16value_and_holderES7_imE_vJSQ_S7_imEJNS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorESH_SI_SI_SI_EEEvOSJ_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES17_
    @     0x7f92db403469  pybind11::cpp_function::dispatcher()
    @     0x7f92e458fb73  PyObject_Call
    @     0x7f92e459ea4d  instancemethod_call
    @     0x7f92e458fb73  PyObject_Call
    @     0x7f92e45e8a84  slot_tp_init
    @     0x7f92e45e533b  type_call
    @     0x7f92e458fb73  PyObject_Call
    @     0x7f92e4624a6e  PyEval_EvalFrameEx
    @     0x7f92e462ba99  PyEval_EvalCodeEx
    @     0x7f92e45b46da  function_call
    @     0x7f92e458fb73  PyObject_Call
    @     0x7f92e45e1f96  slot_tp_new
    @     0x7f92e45e52f5  type_call
    @     0x7f92e458fb73  PyObject_Call
    @     0x7f92e4626119  PyEval_EvalFrameEx
    @     0x7f92e462ba99  PyEval_EvalCodeEx
    @     0x7f92e45b47c7  function_call
    @     0x7f92e458fb73  PyObject_Call
    @     0x7f92e4624a6e  PyEval_EvalFrameEx
    @     0x7f92e462ba99  PyEval_EvalCodeEx
    @     0x7f92e45b47c7  function_call
    @     0x7f92e458fb73  PyObject_Call
    @     0x7f92e4624a6e  PyEval_EvalFrameEx
    @     0x7f92e462ba99  PyEval_EvalCodeEx
    @     0x7f92e45b47c7  function_call

**Comment by KiddoZhu** [comment]
Sorry I haven't seen this situation before. Could you try `conda list graphvite` and check if the signature is cuda92?

**Comment by joshuia** [comment]
`conda list graphvite`
# Name                    Version                   Build  Channel
graphvite                 0.1.0               py27cuda100    milagraph

So it means when I used `conda install -c milagraph graphvite`, it built with cuda 10.0？Could you tell me how to build with cuda 9.2?

**Comment by joshuia** [comment]
OK, I found that `conda install -c milagraph graphvite=0.1.0=py27cuda92` is OK, Thanks!
