### ISSUE TITLE
train knowledge graph model error

### ISSUE THREAD

**Issue by zhoulove259** [DeepGraphLearning/graphvite#12]
### here is my code 

`import graphvite as gv`
`from graphvite.optimizer import Adam,SGD`
`import logging`
`gv.init_logging(logging.DEBUG, verbose=True)`
`edges=[("a","2","c",1),
        ("b","3","c",2),
        ("a","3","b",1)]`
`graph = gv.graph.KnowledgeGraph()`
`graph.load(triplet_list=edges)`
`solver=gv.solver.KnowledgeGraphSolver(dim=128, device_ids=[2], num_sampler_per_worker=4)
solver.build(graph,optimizer=SGD())`
`solver.train(model='RotatE', num_epoch=2000, resume=False, margin=24,l3_regulariation=2e-3,sample_batch_size=2000,positive_reuse=1, adversarial_temperature=2, log_frequency=100)`

### here is error
`W0814 17:32:29.664129 16121 knowledge_graph.cuh:234] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
KnowledgeGraph<uint32>
------------------ Graph -------------------
#entity: 3, #relation: 2
#triplet: 3, normalization: no
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    solver.train(model='RotatE', num_epoch=2000, resume=False, margin=24,l3_regulariation=2e-3,sample_batch_size=2000,positive_reuse=1, adversarial_temperature=2, log_frequency=100)
TypeError: train(): incompatible function arguments. The following argument types are supported:
    1. (self: libgraphvite.solver.KnowledgeGraphSolver, model: str = 'RotatE', num_epoch: int = 2000, resume: bool = False, margin: float = 24, l3_regularization: float = 0.002, sample_batch_size: int = 2000, positive_reuse: int = 1, adversarial_temperature: float = 2, log_frequency: int = 100) -> None

Invoked with: KnowledgeGraphSolver<128, float32, uint32>
----------------- Resource -----------------
#worker: 1, #sampler: 4, #partition: 1
tied weights: yes, episode size: 200
gpu memory limit: 10.8 GiB
gpu memory cost: 162 MiB
----------------- Sampling -----------------
positive sample batch size: 808464432
#negative: 64
----------------- Training -----------------
model: 
optimizer: SGD
learning rate: 0.0001, lr schedule: linear
weight decay: 0
#epoch: 808464432, batch size: 100000
resume: yes
adversarial temperature: 6.40969e-10; kwargs: model='RotatE', num_epoch=2000, resume=False, margin=24, l3_regulariation=0.002, sample_batch_size=2000, positive_reuse=1, adversarial_temperature=2, log_frequency=100`
### i have uninstall graphvite and install again   the same error

**Comment by KiddoZhu** [comment]
There is a typo in your code. The keyword should be `l3_regularization`.

**Comment by zhoulove259** [comment]
i copyed from https://graphvite.io/docs/api/solver.html
