### ISSUE TITLE
Is that possible to load multiple network files using the yaml config?

### ISSUE THREAD

**Issue by PJthunder** [DeepGraphLearning/graphvite#13]
I have a large network and the edge link files are too large to be partitioned into small pieces. Is graphvite able to read network from multiple files and load them?

**Comment by KiddoZhu** [comment]
I am a bit confused. Do you mean the edge list is too large to store in RAM or in a single file?

**Comment by PJthunder** [comment]
I mean the edge files are too large. So I may not be able to feed a single edge files to graphvite. I may need to feed multiple files which contains all the links to the graphvite to run node embedding.

Thanks.

**Comment by KiddoZhu** [comment]
Currently graphvite doesn't support such input format. But why not concat them into a single file? The I/O of the library is fast enough. In our experiments, it can deal with files like 40GB large.

**Comment by PJthunder** [comment]
Never mind. I concats them and trained. It looks fine.
