### ISSUE TITLE
configure: error: An implementation of BLAS is required but none was found

### ISSUE THREAD

**Issue by xzyin** [DeepGraphLearning/graphvite#17]
Hi, I installed graphvite from source with comand
```
cd build && cmake .. && make && cd -
```
but raise
```
checking for /data/opt/anaconda3/envs/graphvite/bin/x86_64-conda_cos6-linux-gnu-c++ -std=c++11 option to support OpenMP... -fopenmp
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking if sgemm_ is being linked in already... no
checking for sgemm_ in -lmkl_intel_lp64... no
checking for sgemm_ in -lmkl... no
checking for sgemm_ in -lopenblas... no
checking for ATL_xerbla in -latlas... no
checking for sgemm_ in -lblas... no
checking for sgemm_ in -framework vecLib... no
checking for sgemm_ in -lcxml... no
checking for sgemm_ in -ldxml... no
checking for sgemm_ in -lscs... no
checking for sgemm_ in -lcomplib.sgimath... no
checking for sgemm_ in -lblas... (cached) no
checking for sgemm_ in -lblas... (cached) no
configure: error: An implementation of BLAS is required but none was found.
make[2]: *** [faiss/src/faiss-stamp/faiss-configure] Error 1
make[1]: *** [CMakeFiles/faiss.dir/all] Error 2
```
just like [issue](https://github.com/facebookresearch/faiss/issues/690) in faiss. but I have install  openblas

my envs:
* CUDA
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
* open blas
```
sudo yum install openblas
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Package openblas-0.3.3-2.el7.x86_64 already installed and latest version
Nothing to do
```
Thanks

**Comment by KiddoZhu** [comment]
Could you describe where such error occurs?

**Comment by xzyin** [comment]
> Could you describe where such error occurs?
Thank you for your reply, I described the problem in detail.

**Comment by KiddoZhu** [comment]
I'm not very familiar about the autoconf routine in faiss. In my case, faiss always works with `mkl`, a kind of BLAS. If you follow the instructions to install the requirements in conda, I think faiss should find `mkl`.

**Comment by bangdo172** [comment]
I had the same problem

**Comment by KiddoZhu** [comment]
@bangdo172 I just checked on a bunch of environments and didn't reproduce this error. I think `mkl` should work if you are using Intel CPUs.

If it still doesn't work, a workaround might be
- manually install openBLAS or mkl
- compile faiss from source
- compile graphvite with `cmake .. -DFAISS_PATH=/path/to/faiss/ && make`

Faiss is only used by the visualization application in graphvite. I will add some compilation options so that you can skip the compilation of faiss.

**Comment by bangdo172** [comment]
> @bangdo172 I just checked on a bunch of environments and didn't reproduce this error. I think `mkl` should work if you are using Intel CPUs.
> 
> If it still doesn't work, a workaround might be
> 
> * manually install openBLAS or mkl
> * compile faiss from source
> * compile graphvite with `cmake .. -DFAISS_PATH=/path/to/faiss/ && make`
> 
> Faiss is only used by the visualization application in graphvite. I will add some compilation options so that you can skip the compilation of faiss.

thank you so much
