### ISSUE TITLE
node2vec implementation "Segmentation fault"

### ISSUE THREAD

**Issue by PJthunder** [DeepGraphLearning/graphvite#18]
My machine has 32core 200 GB memory + 4 Tesla V100. I tried the node2vec config [yaml](https://github.com/DeepGraphLearning/graphvite/blob/master/config/graph/node2vec_youtube.yaml). It reports "segmentation fault" before the training begins. 

The same thing appears when I try to use node2vec to train on another dataset. Is there any bug in the node2vec implementation.

p.s. I choose "auto" for the parameter "num_partition".

**Comment by KiddoZhu** [comment]
It's node2vec's fault. Node2vec uses 2nd order random walk and is less scalable than DeepWalk / LINE in memory cost.

In [benchmarks](https://graphvite.io/docs/benchmark.html), you can find that node2vec can only runs up to 5 million edges.

**Comment by PJthunder** [comment]
So graphvite version of node2vec cannot handle the youtube network, which has 5M edges? Since I try to run the youtube yaml for node2vec but still fails, wondering whether it is due to some bugs in the partition code or it's model capacity.

**Comment by KiddoZhu** [comment]
Sorry, I found the same issue on Youtube. I will check that.

**Comment by KiddoZhu** [comment]
Fixed. Will update it to conda.

**Comment by KiddoZhu** [comment]
Updated to conda.

**Comment by porimol** [comment]
@KiddoZhu 

I'm getting the same error "Segmentation fault"!
