### ISSUE TITLE
Does the graphvite support weighted graph ? 

### ISSUE THREAD

**Issue by zhenhuascut** [DeepGraphLearning/graphvite#27]
I am not sure whether the graphvite support weighted graph. Can you implement the weighted DeepWalk?

**Comment by KiddoZhu** [comment]
Sorry I didn't write it in the document. The system does support weighted graph. For graphs, each line is
`[head] [tail] [weight]`. For knowledge graphs, each line is `[head] [relation] [tail] [weight]`.

**Comment by zhenhuascut** [comment]
Thanks for responding! When I follow the source code today, I found it. I will test some weighted graphs and see how it performs. I will give you the feedback soon.

**Comment by KiddoZhu** [comment]
Fixed in document.
