### ISSUE TITLE
Train TransE, DistMult and RotatE

### ISSUE THREAD

**Issue by zheng-da** [DeepGraphLearning/graphvite#31]
What is a right set of parameters to train TransE, DistMult and RotatE on FB15k to reproduce the results in the RotatE paper?

I started out with the script shown in [the KGE tutorial](https://colab.research.google.com/drive/1TIK-BiMGtlhPNuR2HbSzo_ZOdb40nZiz#forceEdit=true&sandboxMode=true&scrollTo=WhjaZbBOm0s0).
```python
import graphvite as gv
import graphvite.application as gap

app = gap.KnowledgeGraphApplication(dim=512)
app.load(file_name=gv.dataset.fb15k.train)
app.build(optimizer=5e-3, num_negative=4)
app.train(margin=9)

app.link_prediction(file_name=gv.dataset.fb15k.valid,
                    filter_files=[gv.dataset.fb15k.train,
                                  gv.dataset.fb15k.valid,
                                  gv.dataset.fb15k.test])
```
However, this setting cannot train RotatE to reproduce the results in the paper.

**Comment by KiddoZhu** [comment]
For hyperparameters, please refer to the [baseline config files](https://github.com/DeepGraphLearning/graphvite/tree/master/config/knowledge_graph).

The above case only fits the demo dataset `math`. Hyperparameters in KGE are very dataset-dependent and you'd better tune them for each dataset. There is a brief tutorial of hyperparameters at the bottom of [KGE tutorial](https://colab.research.google.com/drive/1TIK-BiMGtlhPNuR2HbSzo_ZOdb40nZiz#forceEdit=true&sandboxMode=true). You may take a look at that.

**Comment by zheng-da** [comment]
thanks
