### ISSUE TITLE
KNNGraph: Aborted (core dumped)

### ISSUE THREAD

**Issue by Ivanaluo** [DeepGraphLearning/graphvite#36]
I am trying to use `graphvite visualize` and extract the vectors after dimension reduction in **largevis**,  thus i install **graphvite** from source, an error is thrown in loading step of graph.KNNGraph:
```
KNNGraph<uint32>
------------------ Graph -------------------
#vertex: 1789406000, #nearest neighbor: 1634496008
perplexity: 1.81753e+31, vector normalization: yes
Faiss assertion 'err == cudaSuccess || err == cudaErrorInvalidValue' failed in int faiss::gpu::getDeviceForAddress(const void*) at gpu/utils/DeviceUtils.cu:105
Aborted (core dumped)

```
OS: Ubuntu 16.04
Graphvite version: 0.2.1
Faiss version: 1.6.0
python3.6   cuda10.1

however, while i use the same dataset in the envs from conda install, it works.
the build process shown as below:
![image](https://user-images.githubusercontent.com/51904290/71776050-7c60c180-2fc5-11ea-9d4c-a93390411a24.png)
![image](https://user-images.githubusercontent.com/51904290/71776055-85519300-2fc5-11ea-933d-837d104ed639.png)

Any help would be grateful.

**Comment by KiddoZhu** [comment]
Hi. The compiling process seems good. Did you modify any C++ source code?

It looks like compatibility issue between graphvite and faiss. Previously graphvite is based on v1.5.1. I will take a look at the latest version.

**Comment by KiddoZhu** [comment]
I just pulled the repo and installed from source, using faiss v1.6.1. `graphvite visualize` worked as expected.

Maybe you have modified some code?

**Comment by Ivanaluo** [comment]
You're right, i haven't modify any c++, its compatibility issue.
I reinstall faiss with v1.4.0 (cuda10.1, graphvite0.2.1), that is absolutely fine!

Many thanks !!
