### ISSUE TITLE
Is Wikidata5m complete/correct?

### ISSUE THREAD

**Issue by dfdazac** [DeepGraphLearning/graphvite#40]
I recently read "KEPLER: A Unified Model for Knowledge Embedding and Pre-trained Language Representation", which proposes the **Wikidata5m** dataset. I found it in this repository, but upon inspection I see that only the Knowledge Graph triples are provided. Do you plan to release the text that you obtained from Wikipedia for this project?

Second, I was checking the data and I found this:

```sh
$ grep Q1000000 wikidata5m.txt
Q1000000        P17     Q794
```

I checked and [Q1000000](https://www.wikidata.org/wiki/Q1000000) corresponds to the Finnish tv series "Matkaoppaat", but this entity does not have an English Wikipedia page, contrary to the way the dataset is described in the paper. Furthermore, [P17](https://www.wikidata.org/wiki/Property:P17) corresponds to "country", and [Q794](https://www.wikidata.org/wiki/Q794) to "Iran", so if I interpret it correctly, this triple is wrong. If this is true, could there be other instances of this issue in `wikidata5m.txt`?

**Comment by KiddoZhu** [comment]
As Kepler hasn't been officially released, the Wikidata5m here is a temporary version for benchmarking GraphVite. For the text data, I guess the author will release it soon.

Your finding is interesting. I am aware that this dataset is a little bit noisy, especially for entities with large IDs. According to my experience, it is still statistically good enough for machine learning. So don't worry.

The knowledge graph here has a few more entities and relations than the one in the paper. It's possible that some entities don't align with Wikipedia.

**Comment by dfdazac** [comment]
I understand, thanks for your reply!
