### ISSUE TITLE
What's the format of config?

### ISSUE THREAD

**Issue by PJthunder** [DeepGraphLearning/graphvite#5]
Looks like users should run through the config file (yaml file) for training/evaluation. But I have no idea what's the format it should be. Could you add some simple examples in the readme file? Maybe just run LINE on karate club network (adjacent matrix/edgelist)?

In addition, it is not very clear what will be included in the output pickle file. Could you please add some simple explanation about that?

**Comment by KiddoZhu** [comment]
For the yaml format, please refer to the [document page](https://graphvite.io/docs/user/configuration.html).

The pickled object is a dict that contains all embeddings, and their index mappings to the original node names. The following lines may help you understand what is in the pickled object.
```
with open("line_blogcatalog.pkl, "rb") as fin:
    blogcatalog = pickle.load(fin)
print(blogcatalog.keys())

names = blogcatalog.id2name
embeddings = blogcatalog.vertex_embeddings
print(names[1024], embddings[1024])
```

**Comment by PJthunder** [comment]
Thank you for your prompt reply. The document is helpful but a little bit confusing to me. So if I want to specify a edge_link file to run. I need to create a single yaml file and change the global yaml file to indicate the dataset path? Also, I am not pretty sure which data format is acceptable for your project.

This information may be stored somewhere in the document. An easy start point in the readme file may still be very helpful for people who only want to calculate the embedding in a short run.

**Comment by KiddoZhu** [comment]
The dataset path in the global yaml file is for downloading/caching standard datasets. You don't necessarily need to modify it in most cases.

To run your own dataset, 
1) Fork an existing yaml.
2) Change dataset paths in `graph`, `evaluation`. It's better to use absolute paths.
3) Change hyperparameters if necessary.

For all applications, the dataset format is strings separated by delimiters. There can be some comment at the end of each line. By default, delimiters are any blank characters, and comment prefix is "#". For node embeddings, the following examples are valid.
1) xxx yyy 1.5 # this is comment
2) xxx yyy # this is comment
The edge weight is optional.

If you're using Python, you can also pass list of `(string, string, float)` to the interface.

Sorry for not clarifying the data formats. We will add documentation of dataset format.

**Comment by PJthunder** [comment]
Thanks for your explanation!
Looks like I just need to provide a common edge list to it.
I have opened another issue about the evaluation file format. I hope it will be easy for you to add a simple documents for that one as well.

**Comment by kalufinnle** [comment]
I also found it a bit confusing of what the desired dataset format should be. Could you add some simple examples in the readme file. Or maybe tutorials on how we can run the codes on our own data? Thank you

**Comment by PJthunder** [comment]
sorry to brother you again. But I don't know what's the input format for LargeViz? I know it should be vectors for nodes, but do not know exactly how the vector should be formatted.

**Comment by KiddoZhu** [comment]
If you call LargeVis from yaml, there are two formats, depending on the task. For graph visualization, it's edge list. For vector visualization, it's a n*d text matrix, i.e. n lines of d-dimensional samples.

The command line `graphvite visualize` is only designed for vector visualization, but you can also pass a numpy dump of n*d matrix as input, with `.npy` suffix.

**Comment by PJthunder** [comment]
Thank you for the quick reply!

**Comment by PJthunder** [comment]
Want to double check. The label file for largevis is just an array (length = n) of string or integer right?

**Comment by KiddoZhu** [comment]
Yes. It can be either n lines of string (*.txt) or a 1d numpy array (*.npy).

**Comment by KiddoZhu** [comment]
Added in v0.2.0
