### ISSUE TITLE
issue with entity_prediction

### ISSUE THREAD

**Issue by gustavopuma** [DeepGraphLearning/graphvite#51]
I trained a model with the following graph:

Robert Hernandez,hasTechnology_Skills,Calendar and scheduling software
Robert Hernandez,hasTechnology_Skills,Autodesk AutoCAD
Robert Hernandez,hasTechnology_Skills,Autodesk Revit
Robert Hernandez,hasOccupation,Engineering Teachers_ Postsecondary
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Finite element analysis software
Engineering Teachers_ Postsecondary,executeTechnology_Skills,The MathWorks MATLAB
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Calendar and scheduling software
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Autodesk AutoCAD
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Autodesk Revit
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Dassault Systemes CATIA
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Dassault Systemes SolidWorks
Engineering Teachers_ Postsecondary,executeTechnology_Skills,PTC Creo Parametric
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Computer aided manufacturing CAM software
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Blackboard Learn
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Course management system software
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Desire2Learn
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Learning management system LMS
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Sakai CLE
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Data entry software
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Email software
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Microsoft Outlook
Engineering Teachers_ Postsecondary,executeTechnology_Skills,DOC Cop
Engineering Teachers_ Postsecondary,executeTechnology_Skills,iParadigms Turnitin
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Web browser software
Engineering Teachers_ Postsecondary,executeTechnology_Skills,Microsoft Office
                                                                                       
I receive predictions with Technology_Skills already related with the person Robert Hernandez but I expected receive predictions not related with him but related with the respective occupation, for example Data entry software its not related with the person but its related with his occupation so when I do :
predictions = app1.entity_prediction(H=["Robert Hernandez"],R=["hasTechnology_Skills"],target="tail",k=25)
I was expecting receive Data entry for example.

**Comment by KiddoZhu** [comment]
It's nature the model predicts existing facts, since it is trained to do so. You may set a sufficient large k, filter predictions overlapped with the training set, and get what you want.

**Comment by gustavopuma** [comment]
Could be very usefull if I pass a full triplet(H,R,T) just the score related to this triplet as top 1. If I dont know the position into the rank I need to pass a very big k or do several predictions ultil find the the related relation I need.

**Comment by KiddoZhu** [comment]
You may call `app.solver.predict(samples)` for this purpose. See [the document](https://graphvite.io/docs/latest/api/solver.html#graphvite.solver.KnowledgeGraphSolver.predict) for details.

Note it's better to batch your predictions, i.e. call `predict()` once with many samples rather than call `predict()` many times.
