### ISSUE TITLE
why run node2vec on graphvite have segmentation fault?

### ISSUE THREAD

**Issue by halzing** [DeepGraphLearning/graphvite#53]
on graphvite,when running node2vec for node embedding always occur segmentation fault and then program will stop before training? but it has error detail, so I don’t know how to solve this problem

**Comment by halzing** [comment]
I try a mini dataset,so Gpu memory should be enough

**Comment by KiddoZhu** [comment]
Node2vec requires much more CPU memory than DeepWalk and LINE.

Could you show the log of GraphVite? How large is your CPU memory?
