### ISSUE TITLE
Evaluation Task

### ISSUE THREAD

**Issue by PJthunder** [DeepGraphLearning/graphvite#7]
I have read over some config files. It looks like all the evaluation for node embedding is node classification. Is that possible to run link prediction task on node embedding tasks?
If so, what's the format of the evaluation file and the config files?

**Comment by KiddoZhu** [comment]
Yes, link prediction is supported for node embedding, although there isn't an example.

You can find the interface [here](https://graphvite.io/docs/api/application.html), in `GraphApplication.link_prediction`. The evaluation file format is
- head tail label
where positive label is 1 and negative label is 0.
If you can't guarantee that evaluation data is exluded in the training set, you can specify the training edge list as `filter_file`.

**Comment by KiddoZhu** [comment]
Added in v0.2.0.
