### ISSUE TITLE
Is the given example on the graphvite.io wrong?

### ISSUE THREAD

**Issue by DoDzilla-ai** [DeepGraphLearning/graphvite#79]
Below the title [Reproduce baseline benchmarks](https://graphvite.io/docs/latest/user/command_line.html#reproduce-baseline-benchmarks) there is an example that states the given example is using 4 GPUs and 12 CPUs but the command line code is this:

`graphvite baseline rotate fb15k --gpu 4 --cpu 3`

I didn't understand how `--cpu 3` means "use 12 CPUs".

**Comment by KiddoZhu** [comment]
Here ``--cpu`` means the number of CPU per GPU.

This design ensures that CPUs can always be equally distributed to GPUs.

**Comment by DoDzilla-ai** [comment]
Ok, now it makes sense. Thank you. I think this explanation should be included somewhere there. This issue can be closed.
