### ISSUE TITLE
Cannot find libgraphvite module

### ISSUE THREAD

**Issue by kalufinnle** [DeepGraphLearning/graphvite#8]
Thanks for releasing the libraries. I tried to run the codes under python folders. And it seems like a module named 'libgraphvite' is missing. I wasn't able to find it myself either. Not sure if it is just my computer.

**Comment by KiddoZhu** [comment]
Are you running in a compiled source? `libgraphvite.so` should lies in `lib/` under the directory you run `make`.

If you followed the instruction to compile the code, I think the Python module should automatically find the file.

**Comment by kalufinnle** [comment]
Yes. I figured it is a problem from my python IDE. Some library dependencies and CUDA was not installed properly into my machine. Thanks!
